name: Build Gradle project

on:
  push:

permissions:
  contents: write

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Run build with Gradle Wrapper
      run: ./gradlew example-plugins:installAll
  release:
    name: Release pushed tag
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "${tag}" \
              "api" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${hehehhehhe}" \
              --generate-notes
